package com.skyler.smarthome.server.enums;

public enum SensorTypes {

    BUTTON, SWITCH, VOLTAGE_GAUGE, CURRENT_GAUGE, LIGHT, WATER, HUMIDITY, TEMPERATURE, SOIL_RESISTANCE, PROXIMITY, PIR, POSITION, KEYBOARD, IR_RECIEVER, ID_CARD, BAR_CODE_SCANNER;
}
